### ISSUE TITLE
空リポジトリの作成をお願いします

### ISSUE THREAD

**Issue by mo646** [zakizaki33/GitTest#8]
一旦環境一式そろえたリポジトリがあったほうがリポジトリのイメージがし易いかなと思います。
空リポジトリと作成していただければ、GitTestの方からコードをコピーしてひとまず動く環境を用意します。

**Comment by zakizaki33** [comment]
おはようございます。

既に作成していたDriveRecorderレポジトリを削除して、あらたに作り直しました。
↓こちらになりますが、意図と違っておりましたらまた連絡をお願いいたします。
https://github.com/zakizaki33/DriveRecorder.git

**Comment by zakizaki33** [comment]
> 一旦環境一式そろえたリポジトリがあったほうがリポジトリのイメージがし易いかなと思います。
> 空リポジトリと作成していただければ、GitTestの方からコードをコピーしてひとまず動く環境を用意します。

おはようございます。

既に作成していたDriveRecorderレポジトリを削除して、あらたに作り直しました。
↓こちらになりますが、意図と違っておりましたらまた連絡をお願いいたします。
https://github.com/zakizaki33/DriveRecorder.git

**Comment by mo646** [comment]
DriveRecorderレポジトリ確認しました！
作成ありがとうございます。
お手数ですが、最初のReadme.mdかなにかファイルを1つ入れてもらってもよいでしょうか。

**Comment by zakizaki33** [comment]
適当にReadme.mdを作成いたしました！

**Comment by zakizaki33** [comment]
> DriveRecorderレポジトリ確認しました！
> 作成ありがとうございます。
> お手数ですが、最初のReadme.mdかなにかファイルを1つ入れてもらってもよいでしょうか。

　適当にReadme.mdを作成いたしました！

**Comment by mo646** [comment]
ありがとうございます！フォーク出来ました
